In [12]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
sent =[
    " the glass of milk",
    "the glass of juice",
    "the cup of tea ",
    "i am a developer",
    "understood the meaning of words",
    "your videos are good"
]

In [14]:
### define the voca size
voc_size =10000

In [15]:
## oen hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr


[[7423, 1442, 2680, 2987],
 [7423, 1442, 2680, 6385],
 [7423, 8486, 2680, 5722],
 [2245, 6745, 2074, 8548],
 [2669, 7423, 4861, 2680, 1769],
 [2312, 1866, 531, 1533]]

In [16]:
from tensorflow.keras.layers import Embedding

from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [17]:
import numpy as np

In [18]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7423 1442 2680 2987]
 [   0    0    0    0 7423 1442 2680 6385]
 [   0    0    0    0 7423 8486 2680 5722]
 [   0    0    0    0 2245 6745 2074 8548]
 [   0    0    0 2669 7423 4861 2680 1769]
 [   0    0    0    0 2312 1866  531 1533]]


In [19]:
## feature representation
dim = 10


In [22]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length =sent_length))
model.compile('adam','mse')

In [24]:
# Run one pass of your embedded docs to build the model
model.predict(embedded_docs)
model.summary()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (6, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[[-0.00013331,  0.03260468,  0.02271446,  0.04077646,
         -0.02330406, -0.03783796,  0.03686675, -0.03209361,
         -0.04436383,  0.00798892],
        [-0.00013331,  0.03260468,  0.02271446,  0.04077646,
         -0.02330406, -0.03783796,  0.03686675, -0.03209361,
         -0.04436383,  0.00798892],
        [-0.00013331,  0.03260468,  0.02271446,  0.04077646,
         -0.02330406, -0.03783796,  0.03686675, -0.03209361,
         -0.04436383,  0.00798892],
        [-0.00013331,  0.03260468,  0.02271446,  0.04077646,
         -0.02330406, -0.03783796,  0.03686675, -0.03209361,
         -0.04436383,  0.00798892],
        [ 0.02704379, -0.00019083, -0.0172891 , -0.01501675,
         -0.03865023, -0.04710368, -0.04933218, -0.03478304,
         -0.02247884,  0.00434613],
        [-0.02758281,  0.01626873, -0.04944624, -0.0495301 ,
         -0.00482597, -0.04878398, -0.00556915, -0.00865102,
          0.01101854, -0.00324657],
        [-0.00141587,  0.00166233, -0.03651776,  0.0